# -*- coding: utf-8 -*-
"""CO3-AT1-Q11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RN6MrCHRfCsWgFnRpwZ9_6oF3pOU6Ipo
"""

from google.colab import files
import cv2
import matplotlib.pyplot as plt

# 1. Upload image
uploaded = files.upload()
file_name = next(iter(uploaded))

# 2. Read image in color and convert to grayscale for processing
img_color = cv2.imread(file_name)    # BGR image
gray = cv2.cvtColor(img_color, cv2.COLOR_BGR2GRAY)

# 3. Canny before smoothing
edges_before = cv2.Canny(gray, 100, 200)

# 4. Gaussian smoothing (5x5 kernel)
smooth = cv2.GaussianBlur(gray, (5, 5), 0)

# 5. Canny after smoothing
edges_after = cv2.Canny(smooth, 100, 200)

# 6. Display results
plt.figure(figsize=(12, 8))

# Original Color Image
plt.subplot(2, 2, 1)
plt.imshow(cv2.cvtColor(img_color, cv2.COLOR_BGR2RGB))
plt.title('Original Color Image', fontsize=12, fontweight='bold')
plt.axis('off')

# Edges Before Smoothing
plt.subplot(2, 2, 2)
plt.imshow(edges_before, cmap='gray')
plt.title('Edges Before Smoothing (Canny)', fontsize=12, fontweight='bold')
plt.axis('off')

# Gaussian Smoothed Image
plt.subplot(2, 2, 3)
plt.imshow(smooth, cmap='gray')
plt.title('Gaussian Smoothed Image (5x5)', fontsize=12, fontweight='bold')
plt.axis('off')

# Edges After Smoothing
plt.subplot(2, 2, 4)
plt.imshow(edges_after, cmap='gray')
plt.title('Edges After Smoothing (Canny)', fontsize=12, fontweight='bold')
plt.axis('off')

plt.tight_layout()
plt.show()
