# -*- coding: utf-8 -*-
"""CO1-AT1-Q16.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eLTQlu8d4A1HSMS8vVfI4BeiQGP6MZ5J
"""

# Q16 - Sampling and Quantization Demonstration

import cv2
import numpy as np
import matplotlib.pyplot as plt
from google.colab import files

# Upload image
uploaded = files.upload()

filename = list(uploaded.keys())[0]

# Read image
img = cv2.imread(filename)
img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

# -----------------------------
# Sampling (Reduce Resolution)
# -----------------------------
sampled = cv2.resize(img, (img.shape[1]//2, img.shape[0]//2))

# -----------------------------
# Quantization (Reduce Color Levels)
# -----------------------------
levels = 16  # Number of intensity levels

quantized = np.floor(img / (256 / levels)) * (256 / levels)
quantized = quantized.astype(np.uint8)

# -----------------------------
# Display
# -----------------------------
plt.figure(figsize=(15,5))

plt.subplot(1,3,1)
plt.imshow(img)
plt.title("Original Image")
plt.axis('off')

plt.subplot(1,3,2)
plt.imshow(sampled)
plt.title("After Sampling")
plt.axis('off')

plt.subplot(1,3,3)
plt.imshow(quantized)
plt.title("After Quantization")
plt.axis('off')

plt.show()

# -----------------------------
# Information
# -----------------------------
print("Original Resolution :", img.shape[:2])
print("Sampled Resolution  :", sampled.shape[:2])

original_size = img.nbytes / 1024
sampled_size = sampled.nbytes / 1024

print(f"\nApprox Memory Usage")
print(f"Original : {original_size:.2f} KB")
print(f"Sampled  : {sampled_size:.2f} KB")

print("\nObservation:")
print("- Sampling reduces image resolution, decreasing storage and computation.")
print("- Quantization reduces intensity levels while preserving most visual quality.")
print("- Together they optimize performance with minimal quality loss.")
