# -*- coding: utf-8 -*-
"""CO3-AT1-Q08.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w0KauYxf0Zf8vvMTgJsK8Vm4G3xec9qV
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt
from google.colab import files

# Upload image
uploaded = files.upload()

# Get uploaded image name
image_name = list(uploaded.keys())[0]

# Read image
img = cv2.imread(image_name, 0)

# Convert image to float32
gray = np.float32(img)

# Harris Corner Detection
corners = cv2.cornerHarris(gray, 2, 3, 0.04)

# Dilate corners for better visibility
corners = cv2.dilate(corners, None)

# Create copies of the original image
all_corners = cv2.cvtColor(img, cv2.COLOR_GRAY2RGB)
selected_corners = cv2.cvtColor(img, cv2.COLOR_GRAY2RGB)

# Detect all corners using lower threshold
threshold1 = 0.01 * corners.max()
all_corners[corners > threshold1] = [255, 0, 0]

# Select only strong corners using higher threshold
threshold2 = 0.05 * corners.max()
selected_corners[corners > threshold2] = [0, 255, 0]

# Display results
plt.figure(figsize=(15, 5))

plt.subplot(1, 3, 1)
plt.imshow(img, cmap="gray")
plt.title("Original Image")
plt.axis("off")

plt.subplot(1, 3, 2)
plt.imshow(all_corners)
plt.title("All Detected Corners")
plt.axis("off")

plt.subplot(1, 3, 3)
plt.imshow(selected_corners)
plt.title("Selected Strong Corners")
plt.axis("off")

plt.tight_layout()
plt.show()
