# -*- coding: utf-8 -*-
"""CV-CO1-AT1-Q18.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nwTVXLQIv5-bKIvoE1tmbrRyxFQVOF2Y
"""

# Q18 - Effect of Improper Quantization in Medical Imaging

import cv2
import numpy as np
import matplotlib.pyplot as plt
from google.colab import files

# -----------------------------
# Upload Image
# -----------------------------
uploaded = files.upload()
filename = list(uploaded.keys())[0]

# Read image in grayscale
img = cv2.imread(filename, cv2.IMREAD_GRAYSCALE)

# -----------------------------
# Quantization Function
# -----------------------------
def quantize(image, levels):
    step = 256 // levels
    quantized = (image // step) * step
    return quantized.astype(np.uint8)

# Different quantization levels
img_256 = img                    # Original (256 levels)
img_64 = quantize(img, 64)
img_16 = quantize(img, 16)
img_4 = quantize(img, 4)

# -----------------------------
# Display Images
# -----------------------------
plt.figure(figsize=(15,8))

plt.subplot(2,2,1)
plt.imshow(img_256, cmap='gray')
plt.title("Original (256 Levels)")
plt.axis('off')

plt.subplot(2,2,2)
plt.imshow(img_64, cmap='gray')
plt.title("64 Intensity Levels")
plt.axis('off')

plt.subplot(2,2,3)
plt.imshow(img_16, cmap='gray')
plt.title("16 Intensity Levels")
plt.axis('off')

plt.subplot(2,2,4)
plt.imshow(img_4, cmap='gray')
plt.title("4 Intensity Levels")
plt.axis('off')

plt.tight_layout()
plt.show()

# -----------------------------
# Histograms
# -----------------------------
plt.figure(figsize=(12,5))

plt.hist(img.ravel(), bins=256, color='black')
plt.title("Histogram of Original Image")
plt.xlabel("Pixel Intensity")
plt.ylabel("Frequency")
plt.show()

plt.figure(figsize=(12,5))

plt.hist(img_4.ravel(), bins=256, color='red')
plt.title("Histogram After 4-Level Quantization")
plt.xlabel("Pixel Intensity")
plt.ylabel("Frequency")
plt.show()

# -----------------------------
# Explanation
# -----------------------------
print("Medical Imaging Observation:")
print("--------------------------------")
print("• Original image contains 256 intensity levels.")
print("• As quantization levels decrease, fine grayscale differences disappear.")
print("• Important tissues and boundaries become less distinguishable.")
print("• Very low quantization (4 levels) introduces false contours (banding).")
print("• In medical imaging, improper quantization may hide tumors, fractures,")
print("  or other critical diagnostic details.")
print("• Therefore, higher intensity resolution is preferred in medical applications.")
