# -*- coding: utf-8 -*-
"""CO3-AT1-Q14.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Rpeqs3RpOXlbmxM4Q4UMuLg99lZ5mUpo
"""

from google.colab import files
import cv2
import matplotlib.pyplot as plt

# 1. Upload image
uploaded = files.upload()
file_name = next(iter(uploaded))

# 2. Read image
img = cv2.imread(file_name)

# Convert BGR to RGB for display
img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

# 3. Create ORB feature detector
orb = cv2.ORB_create(nfeatures=500)

# 4. Define different image scales
scales = [0.5, 1.0, 1.5, 2.0]

images = []
keypoint_images = []
feature_counts = []

# 5. Resize image and detect features at each scale
for scale in scales:

    # Resize image
    resized = cv2.resize(
        img,
        None,
        fx=scale,
        fy=scale,
        interpolation=cv2.INTER_LINEAR
    )

    # Convert resized image to grayscale
    gray = cv2.cvtColor(resized, cv2.COLOR_BGR2GRAY)

    # Detect ORB keypoints and descriptors
    keypoints, descriptors = orb.detectAndCompute(gray, None)

    # Draw detected keypoints
    output = cv2.drawKeypoints(
        resized,
        keypoints,
        None,
        color=(0, 255, 0),
        flags=cv2.DrawMatchesFlags_DRAW_RICH_KEYPOINTS
    )

    # Store results
    images.append(resized)
    keypoint_images.append(output)
    feature_counts.append(len(keypoints))

# 6. Display results
plt.figure(figsize=(14, 10))

for i in range(len(scales)):

    # Display resized image
    plt.subplot(2, 4, i + 1)
    plt.imshow(cv2.cvtColor(images[i], cv2.COLOR_BGR2RGB))
    plt.title(f"Scale = {scales[i]}x")
    plt.axis("off")

    # Display detected features
    plt.subplot(2, 4, i + 5)
    plt.imshow(cv2.cvtColor(keypoint_images[i], cv2.COLOR_BGR2RGB))
    plt.title(f"Features = {feature_counts[i]}")
    plt.axis("off")

plt.tight_layout()
plt.show()

# 7. Display feature count table
print("Feature Detection Results")
print("-" * 35)

for scale, count in zip(scales, feature_counts):
    print(f"Scale {scale}x : {count} keypoints detected")
