# -*- coding: utf-8 -*-
"""CV-CO1-AT1-Q20.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tK5qryTzr0BexdoBLNTdLuupdgN_nVhn
"""

# Q20 - Effect of Sampling Rate and Intensity Resolution

import cv2
import numpy as np
import matplotlib.pyplot as plt
from google.colab import files

# -----------------------------
# Upload Image
# -----------------------------
uploaded = files.upload()
filename = list(uploaded.keys())[0]

# Read image
img = cv2.imread(filename)
img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

# -----------------------------
# Sampling (Resolution)
# -----------------------------
high_sample = img.copy()

medium_sample = cv2.resize(
    img,
    (img.shape[1]//2, img.shape[0]//2),
    interpolation=cv2.INTER_AREA
)

low_sample = cv2.resize(
    img,
    (img.shape[1]//4, img.shape[0]//4),
    interpolation=cv2.INTER_AREA
)

# Enlarge for display only
medium_display = cv2.resize(
    medium_sample,
    (img.shape[1], img.shape[0]),
    interpolation=cv2.INTER_NEAREST
)

low_display = cv2.resize(
    low_sample,
    (img.shape[1], img.shape[0]),
    interpolation=cv2.INTER_NEAREST
)

# -----------------------------
# Intensity Resolution
# -----------------------------
gray = cv2.cvtColor(img, cv2.COLOR_RGB2GRAY)

def quantize(image, levels):
    step = 256 // levels
    return ((image // step) * step).astype(np.uint8)

gray_256 = gray
gray_64 = quantize(gray, 64)
gray_16 = quantize(gray, 16)

# -----------------------------
# Display Sampling Results
# -----------------------------
plt.figure(figsize=(15,5))

plt.subplot(1,3,1)
plt.imshow(high_sample)
plt.title("High Sampling")
plt.axis("off")

plt.subplot(1,3,2)
plt.imshow(medium_display)
plt.title("Medium Sampling")
plt.axis("off")

plt.subplot(1,3,3)
plt.imshow(low_display)
plt.title("Low Sampling")
plt.axis("off")

plt.show()

# -----------------------------
# Display Intensity Resolution
# -----------------------------
plt.figure(figsize=(15,5))

plt.subplot(1,3,1)
plt.imshow(gray_256, cmap='gray')
plt.title("256 Levels")
plt.axis("off")

plt.subplot(1,3,2)
plt.imshow(gray_64, cmap='gray')
plt.title("64 Levels")
plt.axis("off")

plt.subplot(1,3,3)
plt.imshow(gray_16, cmap='gray')
plt.title("16 Levels")
plt.axis("off")

plt.show()

# -----------------------------
# Print Information
# -----------------------------
print("Image Resolution Comparison")
print("----------------------------")
print("Original Resolution :", img.shape[1], "x", img.shape[0])
print("Medium Resolution   :", medium_sample.shape[1], "x", medium_sample.shape[0])
print("Low Resolution      :", low_sample.shape[1], "x", low_sample.shape[0])

print("\nObservation")
print("-----------")
print("• Higher sampling rate preserves edges and fine details.")
print("• Lower sampling rate causes pixelation and loss of detail.")
print("• Higher intensity resolution preserves smooth brightness variations.")
print("• Lower intensity resolution introduces banding and removes subtle details.")
print("\nConclusion:")
print("Applications requiring fine details (medical imaging, satellite images,")
print("biometrics, quality inspection, etc.) should use:")
print("✔ High sampling rate (high spatial resolution)")
print("✔ High intensity resolution (more grayscale/color levels)")
