# -*- coding: utf-8 -*-
"""CV-CO1-AT1-Q17.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uUkyZ7fk9O5z-yidu1dcum4Io9w1GoOs
"""

# Q17 - Uneven Lighting and Contrast Enhancement

import cv2
import numpy as np
import matplotlib.pyplot as plt
from google.colab import files

# Upload image
uploaded = files.upload()

filename = list(uploaded.keys())[0]

# Read image
img = cv2.imread(filename)
img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

# ----------------------------------------
# Create Artificial Uneven Lighting
# ----------------------------------------

height, width = img.shape[:2]

# Horizontal lighting gradient
gradient = np.tile(np.linspace(0.3, 1.0, width), (height, 1))

uneven = img.astype(np.float32)

for i in range(3):
    uneven[:, :, i] = uneven[:, :, i] * gradient

uneven = np.clip(uneven, 0, 255).astype(np.uint8)

# ----------------------------------------
# Histogram Equalization
# ----------------------------------------

gray = cv2.cvtColor(uneven, cv2.COLOR_RGB2GRAY)
equalized = cv2.equalizeHist(gray)

# ----------------------------------------
# CLAHE (Adaptive Histogram Equalization)
# ----------------------------------------

clahe = cv2.createCLAHE(clipLimit=2.0, tileGridSize=(8,8))
clahe_img = clahe.apply(gray)

# ----------------------------------------
# Display Results
# ----------------------------------------

plt.figure(figsize=(16,8))

plt.subplot(2,2,1)
plt.imshow(img)
plt.title("Original Image")
plt.axis("off")

plt.subplot(2,2,2)
plt.imshow(uneven)
plt.title("Uneven Lighting")
plt.axis("off")

plt.subplot(2,2,3)
plt.imshow(equalized, cmap='gray')
plt.title("Histogram Equalization")
plt.axis("off")

plt.subplot(2,2,4)
plt.imshow(clahe_img, cmap='gray')
plt.title("CLAHE (Improved Contrast)")
plt.axis("off")

plt.tight_layout()
plt.show()

# ----------------------------------------
# Explanation
# ----------------------------------------

print("Explanation:")
print("- Uneven lighting occurs due to non-uniform illumination during image formation.")
print("- Some regions receive more light while others receive less, reducing overall contrast.")
print("- Histogram Equalization improves global contrast.")
print("- CLAHE enhances local contrast while preserving details and avoiding over-amplification.")
print("- CLAHE is commonly used in medical imaging and computer vision applications.")
