# -*- coding: utf-8 -*-
"""CV-CO1-AT1-Q19.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VXZNavxSf8by_OhO5i_raYVKgoJ_EQUv
"""

# Q19 - Image Acquisition and Computer Vision Features for Self-Driving Cars

import cv2
import numpy as np
import matplotlib.pyplot as plt
from google.colab import files

# -----------------------------
# Upload Image
# -----------------------------
uploaded = files.upload()

filename = list(uploaded.keys())[0]

# Read image
img = cv2.imread(filename)
img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

# -----------------------------
# Image Acquisition
# -----------------------------
gray = cv2.cvtColor(img, cv2.COLOR_RGB2GRAY)

# -----------------------------
# Noise Reduction
# -----------------------------
blur = cv2.GaussianBlur(gray, (5,5), 0)

# -----------------------------
# Edge Detection
# -----------------------------
edges = cv2.Canny(blur, 50, 150)

# -----------------------------
# Detect Objects using Contours
# -----------------------------
contours, _ = cv2.findContours(edges, cv2.RETR_EXTERNAL,
                               cv2.CHAIN_APPROX_SIMPLE)

detected = img.copy()

for cnt in contours:
    if cv2.contourArea(cnt) > 500:
        x, y, w, h = cv2.boundingRect(cnt)
        cv2.rectangle(detected, (x, y), (x+w, y+h),
                      (255,0,0), 2)

# -----------------------------
# Display Results
# -----------------------------
plt.figure(figsize=(16,10))

plt.subplot(2,2,1)
plt.imshow(img)
plt.title("Original Image (Image Acquisition)")
plt.axis("off")

plt.subplot(2,2,2)
plt.imshow(gray, cmap="gray")
plt.title("Grayscale Image")
plt.axis("off")

plt.subplot(2,2,3)
plt.imshow(edges, cmap="gray")
plt.title("Detected Edges")
plt.axis("off")

plt.subplot(2,2,4)
plt.imshow(detected)
plt.title("Detected Features / Objects")
plt.axis("off")

plt.tight_layout()
plt.show()

# -----------------------------
# Information
# -----------------------------
print("Computer Vision Pipeline")
print("------------------------")
print("1. Camera acquires the road image.")
print("2. Image is converted to grayscale for easier processing.")
print("3. Gaussian Blur removes noise.")
print("4. Canny Edge Detection extracts road boundaries.")
print("5. Contours identify possible vehicles, signs, or obstacles.")
print("6. These visual features help the self-driving system")
print("   make safe driving decisions such as lane keeping,")
print("   obstacle avoidance, and braking.")
