# -*- coding: utf-8 -*-
"""CO3-AT1-Q12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mCJjVPen1K7wdOKyt39EXQkC2G7s62E4
"""

from google.colab import files
import cv2
import numpy as np
import matplotlib.pyplot as plt

# 1. Upload image
uploaded = files.upload()
file_name = next(iter(uploaded))

# 2. Read image in color and convert to grayscale
img_color = cv2.imread(file_name)
gray = cv2.cvtColor(img_color, cv2.COLOR_BGR2GRAY)

# 3. Define Sobel gradient operators
sobel_x = np.array([
    [-1, 0, 1],
    [-2, 0, 2],
    [-1, 0, 1]
], dtype=np.float32)

sobel_y = np.array([
    [-1, -2, -1],
    [ 0,  0,  0],
    [ 1,  2,  1]
], dtype=np.float32)

# 4. Calculate horizontal and vertical gradients
Gx = cv2.filter2D(gray, cv2.CV_32F, sobel_x)
Gy = cv2.filter2D(gray, cv2.CV_32F, sobel_y)

# 5. Calculate gradient magnitude
magnitude = cv2.magnitude(Gx, Gy)

# 6. Calculate gradient direction
direction = cv2.phase(Gx, Gy, angleInDegrees=True)

# 7. Convert gradient magnitude to 8-bit for display
magnitude_display = cv2.convertScaleAbs(magnitude)

# 8. Display results
plt.figure(figsize=(12, 10))

plt.subplot(2, 3, 1)
plt.imshow(cv2.cvtColor(img_color, cv2.COLOR_BGR2RGB))
plt.title("Original Color Image")
plt.axis("off")

plt.subplot(2, 3, 2)
plt.imshow(gray, cmap="gray")
plt.title("Grayscale Image")
plt.axis("off")

plt.subplot(2, 3, 3)
plt.imshow(np.abs(Gx), cmap="gray")
plt.title("Horizontal Gradient (Gx)")
plt.axis("off")

plt.subplot(2, 3, 4)
plt.imshow(np.abs(Gy), cmap="gray")
plt.title("Vertical Gradient (Gy)")
plt.axis("off")

plt.subplot(2, 3, 5)
plt.imshow(magnitude_display, cmap="gray")
plt.title("Gradient Magnitude")
plt.axis("off")

plt.subplot(2, 3, 6)
plt.imshow(direction, cmap="hsv")
plt.title("Gradient Direction")
plt.axis("off")

plt.tight_layout()
plt.show()

# 9. Display sample gradient values
print("Sample Gradient Values:")
print("Gx[100,100] =", Gx[100,100])
print("Gy[100,100] =", Gy[100,100])
print("Magnitude[100,100] =", magnitude[100,100])
print("Direction[100,100] =", direction[100,100], "degrees")
