# -*- coding: utf-8 -*-
"""CO3-AT2-Q10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f2yMBsb6zYI0OEsxutsFBGrrkwoOU-cY
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt
from google.colab import files

# Upload image
uploaded = files.upload()

# Get image name
image_name = list(uploaded.keys())[0]

# Read image in grayscale
img = cv2.imread(image_name, 0)

# Resize image
img = cv2.resize(img, (100, 100))

# Convert image into a vector
data = img.astype(np.float32).reshape(1, -1)

# Create multiple samples with small variations
samples = []

for i in range(20):
    noise = np.random.normal(0, 3, data.shape)
    sample = data + noise
    samples.append(sample.flatten())

samples = np.array(samples, dtype=np.float32)

# Apply PCA with maximum components
mean, eigenvectors = cv2.PCACompute(
    samples,
    mean=None,
    maxComponents=20
)

# Function to reconstruct image using selected components
def reconstruct_image(num_components):

    selected_vectors = eigenvectors[:num_components]

    # Center the data
    centered = samples[0] - mean.flatten()

    # Project onto selected components
    projected = np.dot(centered, selected_vectors.T)

    # Reconstruct
    reconstructed = np.dot(
        projected,
        selected_vectors
    ) + mean.flatten()

    reconstructed = reconstructed.reshape(100, 100)

    return np.clip(reconstructed, 0, 255).astype(np.uint8)


# Reconstruct using different numbers of components
reconstructed_2 = reconstruct_image(2)
reconstructed_5 = reconstruct_image(5)
reconstructed_10 = reconstruct_image(10)
reconstructed_20 = reconstruct_image(20)

# Display results
plt.figure(figsize=(12, 8))

plt.subplot(2, 3, 1)
plt.imshow(img, cmap="gray")
plt.title("Original Image")
plt.axis("off")

plt.subplot(2, 3, 2)
plt.imshow(reconstructed_2, cmap="gray")
plt.title("2 Components")
plt.axis("off")

plt.subplot(2, 3, 3)
plt.imshow(reconstructed_5, cmap="gray")
plt.title("5 Components")
plt.axis("off")

plt.subplot(2, 3, 4)
plt.imshow(reconstructed_10, cmap="gray")
plt.title("10 Components")
plt.axis("off")

plt.subplot(2, 3, 5)
plt.imshow(reconstructed_20, cmap="gray")
plt.title("20 Components")
plt.axis("off")

plt.tight_layout()
plt.show()

print("Original dimensions:", samples.shape[1])
print("Maximum PCA components:", eigenvectors.shape[0])
