# -*- coding: utf-8 -*-
"""CO3-AT2-Q06.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Sl6aQlZr2IBM3MiOzEz2ILHGKkUf77ey
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt
from google.colab import files

# Upload face image
uploaded = files.upload()

# Get image name
image_name = list(uploaded.keys())[0]

# Read image in grayscale
img = cv2.imread(image_name, 0)

# Resize image
img = cv2.resize(img, (100, 100))

# Create multiple samples
samples = []

for i in range(20):
    noise = np.random.normal(0, 5, img.shape)
    sample = img.astype(np.float32) + noise
    sample = np.clip(sample, 0, 255)
    samples.append(sample.flatten())

samples = np.array(samples, dtype=np.float32)

# Apply PCA
mean, eigenvectors = cv2.PCACompute(
    samples,
    mean=None,
    maxComponents=10
)

# Project data onto PCA components
projected = cv2.PCAProject(
    samples,
    mean,
    eigenvectors
)

# Reconstruct the first image manually
reconstructed = np.dot(
    projected[0],
    eigenvectors
) + mean.flatten()

# Reshape reconstructed image
reconstructed = reconstructed.reshape(100, 100)

# Convert values to valid image range
reconstructed = np.clip(reconstructed, 0, 255).astype(np.uint8)

# Display results
plt.figure(figsize=(10, 5))

plt.subplot(1, 2, 1)
plt.imshow(img, cmap="gray")
plt.title("Original Face Image")
plt.axis("off")

plt.subplot(1, 2, 2)
plt.imshow(reconstructed, cmap="gray")
plt.title("PCA Reconstructed Image")
plt.axis("off")

plt.tight_layout()
plt.show()

# Display dimensions
print("Original features:", samples.shape[1])
print("PCA components:", projected.shape[1])
